# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d533cfd4bc8e00528866da355a4235188f09519d442bf90dbceed1ff3359de137cdeba9dc4b9261c57159f9f30e81624fc076c0e038f1bb74c5d89acda73b75b

test:
  secret_key_base: 8fc780f5ab12bc0c91376d95206c8b7332ba6756acb02b0d4f95ab034282854fe8191c3c592c5525d786c3ec6fbfa87ed7e4d57f937ecff15b960e4c6e6166cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
